# Configuration for generating samples
defaults:
  - base_seq
  - _self_
  - paths

inference:
  ckpt_path: null
  seed: 123

  total_samples: 10000
  batch_size: 100
  max_seq_len: 2048
  temperature: 1.0

  # Conditional generation
  target_property: 1.0 # Set to float value for conditional generation (e.g., 2.0, 4.0, etc.)
  
hydra:
  run:
    dir: ${paths.inference_dir}